name: Build docs index

on:
  push:
    branches: [ main ]         

permissions:
  contents: write              

jobs:
  index:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  
    steps:
      - uses: actions/checkout@v4

      - name: Generate index list
        shell: bash
        run: |
          tmp=index.tmp
          echo "<!-- docs-index:start -->"  >  $tmp
          echo ""                            >> $tmp

     
          while IFS= read -r f; do
            [[ $f == README.md ]] && continue
            title=$(grep -m1 '^# ' "$f" | sed 's/^# \+\(.*\)/\1/')
            case "$title" in
              ""|"Table of Contents"|"AWS_Specialty_SCS-C02_notes") continue ;;
            esac
            echo "- [$title]($f)" >> $tmp
          done < <(git ls-files '*.md')

          echo ""                            >> $tmp
          echo "<!-- docs-index:end -->"     >> $tmp

      - name: Patch README.md
        shell: bash
        run: |
          sed -e '/<!-- docs-index:start -->/,/<!-- docs-index:end -->/c\'"$(sed -e 's/[\/&]/\\&/g' -e '$!s/$/\\/' index.tmp)" README.md > README.new
          mv README.new README.md

      - name: Commit changes
        shell: bash
        run: |
          if git diff --quiet; then
            echo "No index changes"
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update global index"
          git push
