# .github/workflows/toc.yml
name: Update TOC

on:
  push:
    branches: [ main ]          
permissions:        
  contents: write
jobs:
  generate-toc:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'   
    steps:
      - uses: actions/checkout@v4

      - uses: technote-space/toc-generator@v4   
        with:
          TARGET_PATHS: README.md,Scenario*_*.md

      - name: Commit changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: update TOC" || exit 0
          git push
